---
- name: Create override directory for {{ autologin_getty_unit }}
  file:
    path: "/etc/systemd/system/{{ autologin_getty_unit }}.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure root autologin on console
  template:
    src: override.conf.j2
    dest: "/etc/systemd/system/{{ autologin_getty_unit }}.d/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart getty
