- name: Setup lxd
  hosts: lxd
  become: true
  tasks:
    - name: Install lxd
      community.general.snap:
        name: lxd
    - name: Configure lxd
      ansible.builtin.command: lxd init --preseed
      args:
        stdin: "{{ lookup('file', 'lxd/lxd-config.yaml') }}"
    - name: Check client certificates
      shell: lxc config trust list | grep 45a67e2a065f
      register: certificate_check
      ignore_errors: true
    - name: Add client certificate
      when: certificate_check.rc != 0
      ansible.builtin.command: lxc config trust add - --name client
      args:
        stdin: "{{ lookup('file', 'lxd/public.crt') }}"
    - name: containers
      community.general.lxd_container: "{{ item }}"
      loop: "{{ containers  }}"
    - name: backup dir
      ansible.builtin.file:
        path: /backup/lxd
        state: directory
        owner: root
        group: root
        mode: '0600'
    - name: backup script
      copy:
        src: lxd/lxd-export.sh
        dest: /etc/cron.daily/lxd-export
        mode: u=rwx,go=rx
        owner: root
        group: root