- hosts: octoprint
  become: true
  tasks:
    - name: install packages
      package:
        name:
          - python3-virtualenv
          - python3-pip
          - python3-dev
          - haproxy
        state: present    

    - name: Add octoprint user
      user:
        name: octoprint
        groups: tty,dialout
        password_lock: true

    - name: Install octoprint
      pip:
        name: octoprint
        virtualenv: ~/venv
      become_user: octoprint

    - name: Start octoprint
      block:
        - name: Copy service
          copy: 
            src: octoprint/octoprint.service
            dest: /etc/systemd/system/octoprint.service
            owner: root
            group: root
            mode: '0644'
        - name: Enable service
          systemd:
            name: octoprint
            state: started
            enabled: true
    
    - name: HAProxy
      block:
        - name: Copy config
          copy:
            src: octoprint/haproxy.cfg
            dest: /etc/haproxy/haproxy.cfg
            owner: root
            group: root
            mode: '0644'
        - name: Enable service
          systemd:
            name: haproxy
            state: started
            enabled: true

    - name: Enable camera
      block:
        - name: start-x
          lineinfile:
            path: /boot/firmware/config.txt
            line: start_x=1
            state: present
          notify: reboot
        - name: gpu-mem
          lineinfile:
            path: /boot/firmware/config.txt
            line: gpu_mem=128
            state: present
          notify: reboot
        - name: packages
          package:
            name:
              - libraspberrypi-bin

    - name: Docker
      block:
        - name: Install required packages
          package:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            state: present
        - name: Add apt key
          ansible.builtin.apt_key:
            id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add apt repository
          apt_repository:
            repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu    focal    stable
            state: present
        - name: install docker
          package:
            name:
              - docker-ce 
              - docker-ce-cli 
              - containerd.io
            state: present

    - name: Restreamer
      block:
        - name: restreamer db directory
          ansible.builtin.file:
            path: /var/lib/restreamer/lib
            state: directory
            mode: '0755'
        - name: restreamer container
          community.docker.docker_container:
            name: restreamer
            image: datarhei/restreamer-aarch64:0.6.8
            restart_policy: unless-stopped
            state: started
            ports:
              - "8080:8080"
            privileged: true
            volumes:
              - /usr:/opt/vc
              - /var/lib/restreamer:/restreamer/db
            env:
              RS_MODE: RASPICAM
              RS_USERNAME: username
              RS_PASSWORD: password
              LD_LIBRARY_PATH: /restreamer/db/lib
              RS_LOGLEVEL: '4'
  handlers:
    - name: reboot
      reboot: