---
- name: Configure Postfix relay
  hosts: postfix_relay
  become: true
  gather_facts: true

  tasks:
    - name: Import postfix_relay role
      import_role:
        name: postfix_relay
      tags: postfix
