ungrouped:
  hosts:
    octoprint:
      ansible_user: ansible
      ansible_host: octoprint.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
    atuin:
      ansible_user: ansible
      ansible_host: atuin.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      nut_server: true
    lu-tze:
      ansible_user: ansible
      ansible_host: lu-tze.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      proxmox_agent: true
    carrot:
      ansible_user: ansible
      ansible_host: carrot.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      zpool_storage: storage
      netplan_enabled: true
      netplan_config_file: /etc/netplan/00-init.yaml
      netplan_configuration:
        network:
          ethernets:
            eno1:
              dhcp4: true
            eno2:
              dhcp4: true
              optional: true
            eno3:
              dhcp4: true
              optional: true
            eno4:
              dhcp4: true
              optional: true
          vlans:
            eno1.30:
              id: 30
              link: eno1

k3s_nodes:
  hosts:
    vimes:
      ansible_user: ansible
      ansible_host: 10.0.1.5
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
      disk_storage: /dev/sdb
      proxmox_agent: true
    dibbler:
      ansible_user: ansible
      ansible_host: dibbler.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      k3s_agent:
        node-label:
          - "rfxtrx=true"
          - "conbee=true"
          - "zwavejs=true"
        node-taint:
          - "node=small:NoSchedule"
