ungrouped:
  hosts:
    octoprint:
      ansible_user: ansible
      ansible_host: octoprint.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3

k3s_nodes:
  hosts:
    carrot:
      ansible_user: ansible
      ansible_host: carrot.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      nut_server: true
      k3s_control_node: true
      k3s_zfs:
        pool: storage
        agent_volume: true
        storage: true
      netplan_enabled: true
      netplan_config_file: /etc/netplan/00-init.yaml
      netplan_configuration:
        network:
          ethernets:
            eno1:
              dhcp4: true
            eno2:
              dhcp4: true
              optional: true
            eno3:
              dhcp4: true
              optional: true
            eno4:
              dhcp4: true
              optional: true
          vlans:
            eno1.124:
              id: 124
              link: eno1
    dibbler:
      ansible_user: ansible
      ansible_host: dibbler.hem.ingenstans.se
      ansible_python_interpreter: /usr/bin/python3
      k3s_agent:
        node-label:
          - "rfxtrx=true"
          - "conbee=true"
          - "zwavejs=true"
        node-taint:
          - "node=small:NoSchedule"
