roles:
  - name: xanmanning.k3s
    version: v3.2.0
  - name: mrlesmithjr.netplan
    version: v0.3.0

collections:
  - name: community.general
    version: 2.1.0
  - name: community.docker
    version: 1.2.2
  - name: ansible.posix
    version: 1.1.1
