- name: Build a k3s cluster
  hosts: k3s_nodes
  vars:
    k3s_become_for_all: true
    k3s_release_version: v1.19.4+k3s1
    k3s_server:
      cluster-cidr: 172.31.0.0/16
      service-cidr: 172.30.0.0/16
      cluster-dns: '172.30.0.10'
      flannel-backend: 'ipsec'
      disable:
       - servicelb
  tasks:
    - name: copy manifests
      when: k3s_control_node is defined and
            k3s_control_node == True
      become: yes
      block:
        - name: create rancher directory
          ansible.builtin.file:
            path: /var/lib/rancher/
            state: directory
            mode: '0755'
        - name: create manifests directory
          ansible.builtin.file:
            path: /var/lib/rancher/k3s/server/manifests/
            state: directory
            mode: '0700'
        - name: copy traefik config
          copy:
            src: k3s/traefik-config.yaml
            dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
            mode: '0644'
    - name: k3s-role
      import_role:
        name: xanmanning.k3s