- hosts: octoprint
  become: true
  tasks:
    - name: install packages
      package:
        name:
          - python3-virtualenv
          - python3-pip
          - python3-dev
        state: present    

    - name: Add octoprint user
      user:
        name: octoprint
        groups: tty,dialout
        password_lock: true

    - name: Install octoprint
      pip:
        name: octoprint
        virtualenv: ~/venv
      become_user: octoprint

    - name: Start octoprint
      block:
        - name: Copy service
          copy: 
            src: octoprint/octoprint.service
            dest: /etc/systemd/system/octoprint.service
            owner: root
            group: root
            mode: '0644'
        - name: Enable service
          systemd:
            name: octoprint
            state: started
            enabled: true
